---
title: "Los Angeles County Regional Economic Profile"
subtitle: "CPLN 620: Techniques of Urban Economic Development"
output: html_document
authors: 'Myron Bañez,Lynn Chong, Jia Wei'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidycensus)
library(sf)
library(tidyverse)
library(sf)
library(lubridate)
library(tigris)
library(gganimate)
library(riem)
library(gridExtra)
library(knitr)
library(kableExtra)
library(mapview)
library(tidycensus)
library(ggcorrplot)
library(RColorBrewer)
library(stargazer)
library(ggplot2)
library("scales")
theme_set(theme_bw())

if(!require(pacman)){install.packages("pacman"); library(pacman)}
p_load(tidyverse, here, janitor)

options(scipen=999)

setwd("~/Desktop/Coding/CPLN_620/Metrics")
```

# Demographics
```{r Migration and Population}
#calling out the data from tidyverse
LA_estimates <- get_estimates(geography = "county", state = "CA", product = "population",
                                  time_series = TRUE, output = "tidy") ##the state command allows me to only bring out the state data, not all of US
LA_comps <- get_estimates(geography = "county", state = "CA", product = "components",
                              time_series = TRUE, output = "tidy")


#standardize the column names
LA_estimates <- clean_names(LA_estimates, "snake")
LA_comps <- clean_names(LA_comps, "snake") #snake makes everything lowercase and put an underscore to it

#filtering out the specific population data that we want
LA_estimates <- LA_estimates %>%
  filter(variable == "POP" & geoid == "06037")
LA_comps <- LA_comps %>%
  filter(geoid == "06037")

LA_estimates <- LA_estimates %>%
   slice(1:11) %>%
  mutate(year = case_when(date == "1" ~ 2010,
                         date == "2" ~ 2011,
                         date == "3" ~ 2012,
                         date == "4" ~ 2013,
                         date == "5" ~ 2014,
                         date == "6" ~ 2015,
                         date == "7" ~ 2016,
                         date == "8" ~ 2017,
                         date == "9" ~ 2018,
                         date == "10" ~ 2019,
                         date == "11" ~ 2020)) 


## plotting out estimates from data we pulled above
pop_plot1 <- ggplot(LA_estimates, aes(x = year, y = value)) +
  geom_line() +
  theme_minimal() +
  labs(x = "Year", y = "Population") +
  scale_x_continuous(breaks = c(2010:2020)) +
  scale_y_continuous(labels = scales::comma)
pop_plot1


palette2 <- c("#95b8d1", "#b8e0d2")
## plotting population components
natural_increase <- LA_comps %>%
  filter(variable == "NATURALINC" | variable == "NETMIG") %>%
  mutate(year = case_when(period == "1" ~ 2010,
                          period == "2" ~ 2011,
                          period == "3" ~ 2012,
                          period == "4" ~ 2013,
                          period == "5" ~ 2014,
                          period == "6" ~ 2015,
                          period == "7" ~ 2016,
                          period == "8" ~ 2017,
                          period == "9" ~ 2018,
                          period == "10" ~ 2019)) # we are alos pulling net migration, so we can compare them

nat_increase_plot <- ggplot(natural_increase, aes(x = year, y = value,
                                                  group = variable, fill = variable)) +
  geom_col(position = "stack") +
  theme_minimal() +
  theme(legend.position = "bottom", legend.text = element_text(size = 8),
        legend.title = element_text(size = 10)) +
  labs(x = "Year", y = "Population", title = "National Increase/Net Migration in Los Angeles County",
       caption = "(Source: US Census Population Estimates, 2010-2019)") +
  geom_hline(yintercept = 0) +
  scale_x_continuous(breaks = c(2010:2019)) +
  scale_y_continuous(labels = scales::comma) +
  scale_fill_manual(values = palette2,
                      name = "Pop. Components",
                      breaks = c("NETMIG", "NATURALINC"),
                      labels = c("Net Migration", "Natural Increase"))
nat_increase_plot


#now the same for migration
migration <- LA_comps %>%
  filter(variable == "DOMESTICMIG"| variable == "INTERNATIONALMIG") %>%
  mutate(year = case_when(period == "1" ~ 2010,
                          period == "2" ~ 2011,
                          period == "3" ~ 2012,
                          period == "4" ~ 2013,
                          period == "5" ~ 2014,
                          period == "6" ~ 2015,
                          period == "7" ~ 2016,
                          period == "8" ~ 2017,
                          period == "9" ~ 2018,
                          period == "10" ~ 2019))

migration_plot <- ggplot(migration, aes(x = year, y = value,
                                        group = variable, fill = variable)) +
  geom_col(position = "stack") +
  theme_minimal() +
  theme(legend.position = "bottom", legend.text = element_text(size = 8),
        legend.title = element_text(size = 10)) +
  labs(x = "Year", y = "Population", title = "Domestic/International Migration in Los Angeles County",
       caption = "(Source: US Census Population Estimates, 2010-2019)") +
  geom_hline(yintercept = 0) +
  scale_x_continuous(breaks = c(2010:2019)) +
  scale_y_continuous(labels = scales::comma) +
  scale_fill_manual(values = palette2,
                    name = "Pop. Components",
                      breaks = c("DOMESTICMIG", "INTERNATIONALMIG"),
                      labels = c("Domestic", "International"))

migration_plot

##POPULATION PYRAMIDS##
LA_vars <- load_variables(year = 2020, dataset = "acs5", cache = TRUE)
LA_age <- get_acs(geography = "county", state = "CA", table = "B01001",
                      year = 2020)

#cleaning it up
LA_age <- LA_age %>%
  clean_names("snake") %>%
  filter(geoid == "06037")

#make new column that is total population to make calculating percentages easier; then drop the total population from this table
LA_age <- LA_age %>%
  mutate(tot_pop = 10040682) %>% #I'm making a new column with just the total population so I can use it to find percentage later
  filter(variable != "B01001_001" & variable != "B01001_002" & variable != "B01001_026") 
  #keep every variable except for ones that I've listed here
  #we just dropped total population, total male population, and total female population, cz we don't need those for the population pyramid

#renaming age and sex variables with informative names
agegroups <- c("0-4", "5-9", "10-14", "15-17", "18-19",
               "20", "21", "22-24", "25-29", "30-34",
               "35-39", "40-44", "45-49", "50-54", "55-59",
               "60-61", "62-64", "65-66", "67-69", "70-74", "75-79",
               "80-84", "85+")

agesex <- c(paste("Male", agegroups),
            paste("Female", agegroups))

LA_age <- LA_age %>%
  mutate(age_sex_groups = rep(agesex, length(unique(name))))

LA_age <- LA_age %>%
  mutate(pop_share = estimate/tot_pop) %>%
  select(estimate, age_sex_groups, pop_share)

#split out age_sex_groups column
LA_age2 <- LA_age %>%
  separate(age_sex_groups, into = c("sex", "age"), sep = " ") %>%
  mutate(age = factor(age, levels = unique(age)),
         percent = ifelse(sex == "Female", pop_share, -pop_share))


##plotting the pyramid!
#setting up the labels
xlabs <- c("0-4", "5-9", "10-14", "15-17", "18-19",
           "20", "21", "22-24", "25-29", "30-34",
           "35-39", "40-44", "45-49", "50-54", "55-59",
           "60-61", "62-64", "65-66", "67-69",
           "70-74", "75-79", "80-84", "85+")

ggplot(LA_age2, aes(x = age, y = percent, fill = sex)) +
  geom_col(width = .9, alpha = .75) +
  scale_y_continuous(breaks = c(-.04, 0, .04),
                     labels = c("4%", "0%", "4%")) +
  coord_flip() +
  theme_minimal() +
  scale_x_discrete(labels = xlabs) +
  scale_fill_manual(values = palette2) +
  theme(strip.text.x = element_text(size = 6)) +
  labs(x = "", y = "", fill = "", title = "Population Pyramid in Los Angeles County",
       caption = "(Source: American Community Survey,\n2016-2020 using tidycensus)")
```

```{r Education and Race}
#bring in data
LA_vars <- load_variables(year = 2020, dataset = "acs5", cache = TRUE)
LA_race <- get_acs(geography = "county", table = "B02001",
                      year = 2020)

LA_race <- LA_race %>%
  clean_names("snake") %>%
  filter(geoid == "06037")

LA_race <- LA_race %>%
  mutate(tot_pop = 10040682) %>%
  filter(variable != "B02001_001" & variable != "B02001_009" & variable != "B02001_010")

#bar chart 1
race <- c("White alone", "Black/African American alone", "American Indian and Alaska Native alone", 
        "Asian alone", "Native Hawaiian and Other Pacific Islander alone", "Some other race alone", 
        "Two or more races")

palette <- c("#95b8d1")
race_chart_1 <- ggplot(LA_race, aes(x=race, y=estimate)) + 
  geom_bar(stat = "identity", width=0.5, fill = "#95b8d1") +
  labs(title = "Breakdown of Race in Los Angeles County 2020", 
         subtitle="(Source: ACS 2020)") +
  xlab("Race") + ylab("Count") +
  scale_x_discrete(guide = guide_axis(angle = 45)) +
  scale_y_continuous(label=comma)

plot(race_chart_1)

#bar chart 2
LA_race_2 <- LA_race %>%
  mutate(pop_share = 100*(estimate/tot_pop))

race_chart_2 <- ggplot(LA_race_2, aes(x=race, y=pop_share)) + 
  geom_bar(stat = "identity", width=0.5, fill = "#95b8d1") +
  labs(title = "Breakdown of Race in Los Angeles County 2020", 
       subtitle="(Source: ACS 2020)") +
  xlab("Race") + ylab("Share (%)") +
  scale_x_discrete(guide = guide_axis(angle = 45))

plot(race_chart_2)

palette_con <- c("#809bce","#95b8d1","#b8e0d2","#d6eadf","#eac4d5", "#a8dadc", "#457b9d")
palette_con1 <- c("#809bce","#95b8d1","#b8e0d2","#d6eadf","#eac4d5", "#a8dadc", "#457b9d", "#1d3557")

#pie chart
race_chart_3 <- ggplot(LA_race_2, aes(x = "", y = pop_share, fill = race)) +
  geom_col() +
  coord_polar(theta = "y") +
  scale_fill_manual(values=palette_con,
                    name = "Race") +
  theme_void() +
  labs(title = "Breakdown of Race in Los Angeles County 2020", 
       subtitle="(Source: ACS 2020)") 

plot(race_chart_3)
################################# QUESTION 2 ###############################
library(tidyr)

#bring in data
LA_vars <- load_variables(year = 2020, dataset = "acs5", cache = TRUE)
LA_edu <- get_acs(geography = "county", table = "B15003",
                   year = 2020)


LA_edu <- LA_edu %>%
  clean_names("snake") %>%
  filter(geoid == "06037")

LA_edu <- LA_edu %>%
  mutate(tot_pop_over25 = 6909179) %>%
  filter(variable != "B15003_001")

LA_edu <- LA_edu %>%
  mutate(edu = case_when(variable == "B15003_002" ~ "1",
                         variable == "B15003_003" ~ "1",
                         variable == "B15003_004" ~ "1",
                         variable == "B15003_005" ~ "1",
                         variable == "B15003_006" ~ "1",
                         variable == "B15003_007" ~ "1",
                         variable == "B15003_008" ~ "1",
                         variable == "B15003_009" ~ "1",
                         variable == "B15003_010" ~ "1",
                         variable == "B15003_011" ~ "1",
                         variable == "B15003_012" ~ "1",
                         variable == "B15003_013" ~ "1",
                         variable == "B15003_014" ~ "1",
                         variable == "B15003_015" ~ "1",
                         variable == "B15003_016" ~ "1",
                         variable == "B15003_017" ~ "2",
                         variable == "B15003_018" ~ "2",
                         variable == "B15003_019" ~ "3",
                         variable == "B15003_020" ~ "3",
                         variable == "B15003_021" ~ "4",
                         variable == "B15003_022" ~ "5", 
                         variable == "B15003_023" ~ "6", 
                         variable == "B15003_024" ~ "7", 
                         variable == "B15003_025" ~ "8"))

LA_edu <- LA_edu %>%
  group_by(edu, name) %>%
  summarize(estimate = sum(estimate, na.rm = T)) %>%
  mutate(Edu_Attainment = case_when(edu == "1" ~ "Less than high school",
                                    edu == "2" ~ "High school diploma", 
                                    edu == "3" ~ "Some college",
                                    edu == "4" ~ "Associate's degree",
                                    edu == "5" ~ "Bachelor's degree",
                                    edu == "6" ~ "Master's degree",
                                    edu == "7" ~ "Professional degree",
                                    edu == "8" ~ "Doctoral degree"))

LA_edu <- LA_edu %>%
  mutate(percent = (estimate / 6909179) * 100)

LA_edu$percentage <- format(round(LA_edu$percent,digits=2),nsmall=2)


#plot stacked bar chart

LA_edu$edu <- as.numeric(as.character(LA_edu$edu))

LA_edu$Edu_Attainment <- factor(LA_edu$Edu_Attainment, levels = LA_edu$Edu_Attainment)


ggplot(LA_edu, aes(fill=Edu_Attainment, y=percentage, x=name)) + 
  geom_bar(position="stack", stat="identity") +
  labs(title = "Educational Attainment in Los Angeles County", x = "Region", y = "Estimate", subtitle="(Source: ACS 2020)") +
  scale_fill_manual(name = "Educational Attainment", values = palette_con1) +
  geom_text(aes(label = percentage), colour = "black", position = position_stack(vjust=0.5)) +
  theme(axis.ticks = element_blank(), axis.text.y = element_blank(), axis.line.y = element_blank()) 
```

```{r Income}
LA_vars <- load_variables(year = 2020, dataset = "acs5", cache = TRUE)
LA_HHincome <- get_acs(geography = "county", table = "B19001",
                       year = 2020)


LA_HHincome <- LA_HHincome %>%
  clean_names("snake") %>%
  filter(geoid == "06037")

LA_HHincome <- LA_HHincome %>%
  mutate(tot_HH = 3332504) %>%
  filter(variable != "B19001_001") %>%
  mutate(HH_share = 100*(estimate/tot_HH))


LA_HHincome <- LA_HHincome %>%
  mutate(income = case_when(variable == "B19001_002" ~ "Less than $10,000",
                            variable == "B19001_003" ~ "$10,000 to $14,999",
                            variable == "B19001_004" ~ "$15,000 to $19,999",
                            variable == "B19001_005" ~ "$20,000 to $24,999",
                            variable == "B19001_006" ~ "$25,000 to $29,999",
                            variable == "B19001_007" ~ "$30,000 to $34,999",
                            variable == "B19001_008" ~ "$35,000 to $39,999",
                            variable == "B19001_009" ~ "$40,000 to $44,999",
                            variable == "B19001_010" ~ "$45,000 to $49,999",
                            variable == "B19001_011" ~ "$50,000 to $59,999",
                            variable == "B19001_012" ~ "$60,000 to $74,999",
                            variable == "B19001_013" ~ "$75,000 to $99,999",
                            variable == "B19001_014" ~ "$100,000 to $124,999",
                            variable == "B19001_015" ~ "$125,000 to $149,999",
                            variable == "B19001_016" ~ "$150,000 to $199,999",
                            variable == "B19001_017" ~ "$200,000 or more"))

LA_HHincome$income <- factor(LA_HHincome$income, levels = LA_HHincome$income)

# plot
HH_income_plot1 <- ggplot(LA_HHincome, aes(x=income, y=HH_share)) + 
  geom_bar(stat = "identity", width=0.5, fill = "#95b8d1") +
  xlab("Income") + ylab("Share (%)") +
  labs(title = "Share of Groups of Household Income in Los Angeles County", subtitle="(Source: ACS 2020)") +
  scale_x_discrete(guide = guide_axis(angle = 45))

plot(HH_income_plot1)

##HH income by race

acs_key <- census_api_key("2c4935a80c5f16c67ae2b5625590ce36fc6be252", overwrite = TRUE)

LA_HHincome_all <- get_acs(geography = "county", table = "B19013",
                       year = 2020) %>%
  clean_names("snake") %>%
  filter(geoid == "06037")

LA_HHincome_white <- get_acs(geography = "county", table = "B19013A",
                       year = 2020) %>%
  clean_names("snake") %>%
  filter(geoid == "06037")
 
LA_HHincome_black <- get_acs(geography = "county", table = "B19013B",
                       year = 2020) %>%
  clean_names("snake") %>%
  filter(geoid == "06037")

LA_HHincome_americanindian <- get_acs(geography = "county", table = "B19013C",
                       year = 2020) %>%
  clean_names("snake") %>%
  filter(geoid == "06037")

LA_HHincome_asian <- get_acs(geography = "county", table = "B19013D",
                       year = 2020) %>%
  clean_names("snake") %>%
  filter(geoid == "06037")

LA_HHincome_pacific <- get_acs(geography = "county", table = "B19013E",
                       year = 2020) %>%
  clean_names("snake") %>%
  filter(geoid == "06037")

LA_HHincome_other <- get_acs(geography = "county", table = "B19013F",
                       year = 2020) %>%
  clean_names("snake") %>%
  filter(geoid == "06037")

LA_HHincome_twoplus <- get_acs(geography = "county", table = "B19013G",
                             year = 2020) %>%
  clean_names("snake") %>%
  filter(geoid == "06037")

LA_HHincome_white_non_hispanic <- get_acs(geography = "county", table = "B19013H",
                             year = 2020) %>%
  clean_names("snake") %>%
  filter(geoid == "06037")

LA_HHincome_other_hispanic <- get_acs(geography = "county", table = "B19013I",
                             year = 2020) %>%
  clean_names("snake") %>%
  filter(geoid == "06037")


LA_HH_income_by_race <- rbind(LA_HHincome_white, LA_HHincome_black, LA_HHincome_americanindian,
                            LA_HHincome_asian, LA_HHincome_pacific, LA_HHincome_other, LA_HHincome_twoplus,
                            LA_HHincome_white_non_hispanic, LA_HHincome_other_hispanic) %>%
  mutate(houserholder = case_when(
                         variable == "B19013A_001" ~ "White alone",
                         variable == "B19013B_001" ~ "Black or African American alone",
                         variable == "B19013C_001" ~ "American Indian and Alaska Native alone",
                         variable == "B19013D_001" ~ "Asian alone",
                         variable == "B19013E_001" ~ "Native Hawaiian and other Pacific Islander alone",
                         variable == "B19013F_001" ~ "Some other race alone",
                         variable == "B19013G_001" ~ "Two or more races",
                         variable == "B19013H_001" ~ "White alone, not Hispanic or Latino",
                         variable == "B19013I_001" ~ "Hispanic or Latino"))


HH_income_by_race_plot1 <- ggplot(LA_HH_income_by_race, aes(x=reorder(houserholder,estimate), y=estimate)) + 
  geom_bar(stat = "identity", width=0.5, fill="#95b8d1") +
  xlab("Race/Ethnicity of Householder") + ylab("Median Household Income in the \nPast 12 Months ($)") +
  scale_x_discrete(guide = guide_axis(angle = 45)) +
  scale_y_continuous(label=comma) + 
  labs(title = "Median Household Income by Race or Ethnicity in Los Angeles County", subtitle = "(Source: ACS 2020)") + theme_bw()

plot(HH_income_by_race_plot1)
```

# Business Structure
```{r MSA, eval=TRUE, echo=TRUE, warning=FALSE, message=FALSE}
qwi_msa <- read_csv("qwi_msa.csv")

qwi_msa <- clean_names(qwi_msa, case = "snake")

qwi_annual <- qwi_msa %>%
  group_by(year, industry_label_value) %>%
  summarise(avg_emp = mean(emp_total, na.rm = TRUE),
            avg_earnings = mean(earn_s, na.rm = TRUE))

qwi_tot_wide <- qwi_annual %>%
  pivot_wider( names_from = year,
  values_from = c("avg_emp", "avg_earnings"),
  values_fill = 0)

qwi_tot_wide <- qwi_tot_wide %>%
  mutate(emp_growth = (avg_emp_2021 - avg_emp_2011)/avg_emp_2011,
  pay_growth = (avg_earnings_2021 - avg_earnings_2011)/avg_earnings_2011)
```

```{r National, eval=TRUE, echo=TRUE, warning=FALSE, message=FALSE}
qwi_national <- read_csv("qwi_national.csv")
qwi_national <- qwi_national %>% clean_names(case = "snake")

qwi_nat_annual <- qwi_national %>%
  group_by(industry_label_value, geography_label_value, year) %>%
  summarise(avg_emp = mean(emp_total, na.rm = TRUE),
            avg_earnings = mean(earn_s, na.rm = TRUE)) %>%
ungroup() %>%
group_by(industry_label_value, year) %>%
summarise(avg_emp = sum(avg_emp, na.rm = TRUE),
avg_earnings = sum(avg_earnings, na.rm = TRUE))

qwi_nat_annual_wide <- qwi_nat_annual %>%
  pivot_wider( names_from = year,
  values_from = c("avg_emp", "avg_earnings"),
  values_fill = 0)

qwi_annual_wide1 <- qwi_tot_wide %>%
  inner_join(qwi_nat_annual_wide, by = "industry_label_value",
  suffix = c("_msa", "_national"))

qwi_annual_wide1 <- qwi_annual_wide1 %>%
  ungroup() %>%
  mutate(lq_2011 = (avg_emp_2011_msa/sum(avg_emp_2011_msa, na.rm = TRUE))/(avg_emp_2011_national/sum(avg_emp_2011_national,na.rm=TRUE)),
         lq_2021 = (avg_emp_2021_msa/sum(avg_emp_2021_msa, na.rm = TRUE))/(avg_emp_2021_national/sum(avg_emp_2021_national,na.rm=TRUE)))
```

```{r Growing Chart, eval=TRUE, echo=TRUE, warning=FALSE, message=FALSE}
la_top5 <- qwi_tot_wide[order(qwi_tot_wide$emp_growth,decreasing=T)[1:5],]
la_btm5 <- qwi_tot_wide[order(qwi_tot_wide$emp_growth,decreasing=F)[1:5],]

la_5 <- rbind(la_top5,la_btm5)

la_5$emp_growth <- round(la_5$emp_growth, 2)

la_5 %>% 
  summarize(Industry = industry_label_value,
    Growth = emp_growth)%>%
    arrange(desc(Growth)) %>%
  kable(title = "Top 5 Fastest Growing Industries", caption = "Top 5 Fastest Growing and Most Declining Industries in Los Angeles County \n (Source: QWI Data 2011 & 2021)") %>%
  kable_styling("striped",full_width = F) %>%
  row_spec(1:5, background = '#95b8d1') %>%
  row_spec(0, bold=TRUE) %>%
  column_spec(2, bold=TRUE)
```

```{r Declining Chart, eval=TRUE, echo=TRUE, warning=FALSE, message=FALSE, fig.height=3, fig.width=9}
la_5$`Industry` <- rownames(la_5)  # create new column for car names

la_5$score <- round(la_5$emp_growth, 2)  # compute normalized mpg

la_5 <-
  la_5 %>% 
  mutate(score_norm = case_when(emp_growth < 0 ~ "below",
                          TRUE ~ "above"))

la_5 <- la_5[order(la_5$score_norm), ]  # sort

la_5$`Industry` <- factor(la_5$`Industry`, levels = la_5$`Industry`)  # convert to factor to retain sorted order in plo

ggplot(la_5, aes(x=reorder(industry_label_value,score), y=score, label=score)) + 
  geom_bar(stat='identity', aes(fill=score_norm), width=.5)  +
  scale_fill_manual(name="Employment Growth", 
                    labels = c("Above Average", "Below Average"), 
                    values = c("above"="#95b8d1", "below"="#b8e0d2")) + 
  labs(subtitle="(Source: QWI Data 2011 & 2021)", 
       title= "Top 5 Fastest Growing and Most Declining \nIndustries in Los Angeles County",
       x = "Industry", y = "Score") + 
  coord_flip()
```

```{r Concentration One, eval=TRUE, echo=TRUE, warning=FALSE, message=FALSE}
la_contop5 <- qwi_annual_wide1[order(qwi_annual_wide1$lq_2021,decreasing=T)[1:5],]
la_conbtm5 <- qwi_annual_wide1[order(qwi_annual_wide1$lq_2021,decreasing=F)[1:5],]

la_con5 <- rbind(la_contop5,la_conbtm5) %>%
  dplyr::select(industry_label_value,lq_2021)

la_con5$lq_2021 <- format(round(la_con5$lq_2021, 2), nsmall = 2)

la_con5 %>% 
  summarize(Industry = industry_label_value,
    Location_Quotient = lq_2021)%>%
    arrange(desc(Location_Quotient)) %>%
  rename("Location Quotient" = Location_Quotient) %>% 
  kable(title = "Top 5 Fastest Growing Industries", caption = "Top 5 Most and Least Concentrated Industries in Los Angeles County \n (Source: QWI Data 2011 & 2021)") %>%
  kable_styling("striped",full_width = F) %>%
  row_spec(1:5, background = '#95b8d1') %>%
  row_spec(0, bold=TRUE) %>%
  column_spec(2, bold=TRUE)
```

```{r Concentration Two, eval=TRUE, echo=TRUE, warning=FALSE, message=FALSE}
palette_con <- c("#809bce","#95b8d1","#b8e0d2","#d6eadf","#eac4d5")

ggplot(la_contop5, aes(x="", y=lq_2021, fill=industry_label_value)) +
  geom_bar(stat="identity", width=1, color="white") +
  coord_polar("y", start=0) +
  theme_void() +
  scale_fill_manual(values = palette_con,
                    name = "Industry") +
  labs(title = "Share of Top 5 Industries Concentration Score \nin Los Angeles County", caption = "(Source: QWI Data 2011 & 2021)")
```

```{r Wage, eval=TRUE, echo=TRUE, warning=FALSE, message=FALSE}
la_top5pay <- qwi_tot_wide[order(qwi_tot_wide$pay_growth,decreasing=T)[1:5],]
la_btm5pay <- qwi_tot_wide[order(qwi_tot_wide$pay_growth,decreasing=F)[1:5],]

la_5pay <- rbind(la_top5pay,la_btm5pay)

la_5pay$pay_growth <- round(la_5pay$pay_growth, 2)

la_5pay %>% 
  summarize(Industry = industry_label_value,
            Payment = pay_growth)%>%
    arrange(desc(Payment)) %>%
  kable(title = "Top 5 Fastest Growing Industries", caption = "Top 5 Highest & Lowest Paying Industries in Los Angeles County \n(Source: QWI Data 2011 & 2021)") %>%
  kable_styling("striped",full_width = F) %>%
  row_spec(1:5, background = '#95b8d1') %>%
  row_spec(0, bold=TRUE) %>%
  column_spec(2, bold=TRUE)
```

# Regional Economic Change
```{r COS, eval=TRUE, echo=TRUE, warning=FALSE, message=FALSE}
cos_2011 <- .5 * sum(abs(qwi_annual_wide1$avg_emp_2011_msa - 
qwi_annual_wide1$avg_emp_2011_national), na.rm = TRUE)

cos_2021 <- .5 *  sum(abs(qwi_annual_wide1$avg_emp_2021_msa - 
qwi_annual_wide1$avg_emp_2021_national), na.rm = TRUE)

cos_2011 
cos_2021 
```

```{r HHI, eval=TRUE, echo=TRUE, warning=FALSE, message=FALSE}
hhi_2011 <- sum(qwi_annual_wide1$avg_emp_2011_msa^2, na.rm = TRUE)
hhi_2021 <- sum(qwi_annual_wide1$avg_emp_2021_msa^2, na.rm = TRUE)

hhi_2011 
hhi_2021
```

```{r SS, eval=TRUE, echo=TRUE, warning=FALSE, message=FALSE}
qwi_annual_wide1 <- qwi_annual_wide1 %>% 
  select(1:9) %>%
  mutate(emp_change1121 = avg_emp_2021_msa - avg_emp_2011_msa)

qwi_annual_wide1 <- qwi_annual_wide1 %>% 
  mutate(nat_growth = avg_emp_2011_msa * 
  ((sum(avg_emp_2021_national, na.rm = TRUE)/
  sum(avg_emp_2011_national, na.rm = TRUE)) - 1))

qwi_annual_wide1 <- qwi_annual_wide1 %>% 
mutate(ind_mix = avg_emp_2011_msa * 
((avg_emp_2021_national/avg_emp_2011_national) - 
(sum(avg_emp_2021_national, na.rm = TRUE)/sum(avg_emp_2011_national, na.rm = TRUE))))

qwi_annual_wide1 <- qwi_annual_wide1 %>% 
mutate(reg_shift = avg_emp_2011_msa * 
((avg_emp_2021_msa/avg_emp_2011_msa) -
(avg_emp_2021_national/avg_emp_2011_national)))

qwi_annual_wide1 <- qwi_annual_wide1 %>% 
mutate(change = nat_growth + ind_mix + reg_shift)

```

```{r SS Wrangling, eval=TRUE, echo=TRUE, warning=FALSE, message=FALSE}
change_top5 <- qwi_annual_wide1[order(qwi_annual_wide1$change,decreasing=T)[1:5],]
change_btm5 <- qwi_annual_wide1[order(qwi_annual_wide1$change,decreasing=F)[1:5],]

change_top5$year <- 2021
change_btm5$year <- 2021

change_5 <- rbind(change_top5,change_btm5)

change_5$year <- "2021"

change_5 <- change_5[order(change_5$change,decreasing=T)[1:10],]
```

```{r SS Chart}
palette10 <- c("#757bc8","#8187dc","#8e94f2","#9fa0ff","#ada7ff","#bbadff","#cbb2fe","#dab6fc","#ddbdfc","#e0c3fc")

ggplot() + 
    geom_bar(data = change_5, aes(x=year, y=change, fill=industry_label_value),stat = "identity") +
  scale_y_continuous(label=comma) +
    scale_fill_manual(values = palette10,
                    name = "Industry") +
  labs(title = "Top and Bottom 5 Industries with the most employment growth/decline",
       subtitle = "Los Angeles County 2011-2021", caption = "(Source: QWI Data 2011 & 2021)")
```

# Labor Market 1
```{r Load Data}
emp_status <- get_acs(geography = "metropolitan statistical area/micropolitan statistical area",
                      year = 2020,
                      variables = c("White NH" = "S2301_C04_012",
                      "Black NH" = "S2301_C04_013",
                      "Amer. Indian NH" = "S2301_C04_014",
                      "Asian NH" = "S2301_C04_015",
                      "Native Hawaiian NH" = "S2301_C04_016",
                      "Other NH" = "S2301_C04_017",
                      "Two or more NH" = "S2301_C04_018",
                      "Hispanic/Latinx" = "S2301_C04_019"))
```

```{r Employment Data, eval=TRUE, echo=TRUE, warning=FALSE, message=FALSE}
emp_status_us <- get_acs(geography = "us",year = 2020,
                         variables = c("White NH" = "S2301_C04_012",
"Black NH" = "S2301_C04_013",
"Amer. Indian NH" = "S2301_C04_014",
"Asian NH" = "S2301_C04_015",
"Native Hawaiian NH" = "S2301_C04_016",
"Other NH" = "S2301_C04_017",
"Two or more NH" = "S2301_C04_018",
"Hispanic/Latinx" = "S2301_C04_019"))
```

```{r Unemployment, eval=TRUE, echo=TRUE, warning=FALSE, message=FALSE}
la_emp <- emp_status %>%
  filter(GEOID == "31080") %>%
  bind_rows(emp_status_us) %>%
  mutate(NAME = stringr::str_remove(string = NAME,
                                    pattern = ", Los Angeles Metro Area"))

palette2 <- c("#95b8d1", "#b8e0d2")

ggplot(la_emp, aes(variable, estimate, fill = NAME)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(x = "Race/Ethnicity", y = "", title = "Unemployment by Race/Ethnicity in Los Angeles MSA \n(Source: 2020 ACS Data)") +
  
  scale_y_continuous(labels = function(x) paste0(x, "%")) +
  scale_fill_manual(values = palette2) +
  geom_errorbar(aes(ymin = estimate - moe, ymax = estimate + moe),
                width = .75, position = "dodge") +
  coord_flip() +
  theme_minimal() +
  theme(legend.position = "bottom", legend.text = element_text(size = 8))
```

```{r Workers Class, eval=TRUE, echo=TRUE, warning=FALSE, message=FALSE}
worker_class <- get_acs(geography = "metropolitan statistical area/micropolitan statistical area",
variables = c("Total Emp." = "S2408_C01_001",
"Private, for-profit" = "S2408_C01_002",
"Private, not-for-profit" = "S2408_C01_005",
"Local Gov." = "S2408_C01_006",
"State Gov." = "S2408_C01_007",
"Federal" = "S2408_C01_008",
"Self Employed" = "S2408_C01_009"),
year = 2020)
```

```{r Workers Class Wrangling, eval=TRUE, echo=TRUE, warning=FALSE, message=FALSE}
worker_class <- worker_class %>%
  filter(GEOID == "31080") %>%
  mutate(class_share = estimate/6501703)

worker_class_us <- get_acs(geography = "us",
                           variables = c("Total Emp." = "S2408_C01_001",
"Private, for-profit" = "S2408_C01_002",
"Private, not-for-profit" = "S2408_C01_005",
"Local Gov." = "S2408_C01_006",
"State Gov." = "S2408_C01_007",
"Federal" = "S2408_C01_008",
"Self Employed" = "S2408_C01_009"), year = 2020)
worker_class_us <- worker_class_us %>%
mutate(class_share = estimate/155888980)
```

```{r Workers Class Plot, eval=TRUE, echo=TRUE, warning=FALSE, message=FALSE}
worker_class_la <- worker_class %>%
  bind_rows(worker_class_us) %>%
  filter(variable != "Total Emp.")

worker_class_la <- worker_class_la %>%
  mutate(NAME = stringr::str_remove(string = NAME,
                                    pattern = ", Los Angeles Metro Area"))

worker_class_la <- worker_class_la %>%
  mutate(variable = factor(variable,
                           levels = c("Private, for-profit", "Private, not-for-profit", "Local Gov.", 
                                      "State Gov.","Federal", "Self Employed")))

ggplot(worker_class_la, aes(variable, class_share, fill = NAME)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(x = "Employment Status", y = "", title = "Classification of Workers in Los Angeles MSA \n(Source: 2020 ACS Data)") +
  scale_y_continuous(labels = scales::percent) +
  scale_fill_manual(values = palette2) +
  coord_flip() +
  theme_minimal() +
  theme(legend.position = "bottom",
  legend.text = element_text(size = 8))
```

```{r Top Occupations, eval=TRUE, echo=TRUE, warning=FALSE, message=FALSE}
oes <- read_csv("MSAOES.csv")
oes_nat <- read_csv("oes_nat.csv")

oes_data <- oes %>%
  inner_join(oes_nat, by = "Occupation (SOC code)",
  suffix = c("_msa", "_national"))

oes_data <- oes_data %>% 
  rename(emp_msa = "Employment(1)_msa")

oes_data <- oes_data %>% 
  rename(hour_mean_wage_msa = "Hourly mean wage_msa",
         ann_mean_wage_msa = "Annual mean wage(2)_msa",
         emp_national = "Employment(1)_national",
         hour_mean_wage_national = "Hourly mean wage_national",
         ann_mean_wage_national = "Annual mean wage(2)_national")

oes_data <- oes_data %>% 
  rename(Occupation = "Occupation (SOC code)")

oes_data$emp_msa <- as.numeric(as.character(oes_data$emp_msa))
oes_data$hour_mean_wage_msa <- as.numeric(as.character(oes_data$hour_mean_wage_msa))
oes_data$ann_mean_wage_msa <- as.numeric(as.character(oes_data$ann_mean_wage_msa))
oes_data$hour_mean_wage_national <- as.numeric(as.character(oes_data$hour_mean_wage_national))
oes_data$ann_mean_wage_national <- as.numeric(as.character(oes_data$ann_mean_wage_national))

oes_data[is.na(oes_data)] = 0

oes_data <- oes_data %>%
  ungroup() %>%
  mutate(lq = (emp_msa/sum(emp_msa, na.rm = TRUE))/(emp_national/sum(emp_national,na.rm=TRUE)))

oes_data <- oes_data %>%
  ungroup() %>%
  mutate(hour_premium = (hour_mean_wage_msa/hour_mean_wage_national),
         ann_premium = (ann_mean_wage_msa/ann_mean_wage_national))

oes_data <- oes_data[!oes_data$Occupation == "All Occupations(000000)", ]

```

```{r Top Occupations Table, eval=TRUE, echo=TRUE, warning=FALSE, message=FALSE}
oes_10 <- oes_data[order(oes_data$emp_msa,decreasing=T)[1:10],]

oes_10 <- oes_10 %>%
  mutate(across(emp_msa, ~ format(., big.mark = ",", scientific = F)))

oes_10 <- oes_10 %>%
  mutate(across(ann_mean_wage_msa, ~ format(., big.mark = ",", scientific = F)))

oes_10$lq <- format(round(oes_10$lq, 2), nsmall = 2)

oes_10 %>% 
  summarize(Occupation = Occupation,
            Employment = emp_msa,
            "Location Quotient" = lq,
            "Annual Wage" = ann_mean_wage_msa)%>%
    arrange(desc(Employment)) %>%
  kable(title = "Top 10 Occupations", caption = "Top 10 Occupations in Los Angeles MSA \n(Source: OES Data)") %>%
  kable_styling("striped",full_width = F) %>%
  row_spec(1:5, background = '#95b8d1') %>%
  row_spec(0, bold=TRUE) %>%
  column_spec(2:4, bold=TRUE)
```

```{r Top Occupations Plot, eval=TRUE, echo=TRUE, warning=FALSE, message=FALSE}
palette <- c("#95b8d1")
ggplot(oes_10, aes(x = emp_msa, y = reorder(Occupation,emp_msa))) +
  geom_point() +
  scale_x_discrete(guide = guide_axis(angle = 45)) +
  scale_fill_manual(values = palette) +
  labs(x = "Employment",
       y = "Occupation",
       title = "Top 10 Occupations in Los Angeles MSA \n(Source: OES Data)")

```

# Case Study
```{r Manufacturing, eval=TRUE, echo=TRUE, warning=FALSE, message=FALSE}
manufacturing <- read_csv("manufacturing.csv") 
manufacturing <- manufacturing %>%
  mutate(across(count, ~ format(., big.mark = ",", scientific = F)))

manufacturing %>% 
  summarize("Zip Code" = zip,
            Employment = count,
            Share = share)%>%
    arrange(desc(Employment)) %>%
  kable(title = "Top 10 Zip Codes for Manufacturing", caption = "Top 10 Zip Codes for Manufacturing \n(Source: U.S. Census Bureau OnTheMap 2014 & 2019)") %>%
  kable_styling("striped",full_width = F) %>%
  row_spec(1, background = '#95b8d1') %>%
  row_spec(2, background = '#b8e0d2') %>%
  row_spec(0, bold=TRUE) %>%
  column_spec(2, bold=TRUE)
```

```{r Health, eval=TRUE, echo=TRUE, warning=FALSE, message=FALSE}
manufacturing <- read_csv("manufacturing.csv") 
manufacturing <- manufacturing %>%
  mutate(across(count, ~ format(., big.mark = ",", scientific = F)))

health <- read_csv("health.csv") 
health <- health %>%
  mutate(share = (count/62868) * 100)
health <- health %>%
  mutate(across(count, ~ format(., big.mark = ",", scientific = F)))
health$share <- format(round(health$share, 1), nsmall = 1)


manufacturing  %>% 
  summarize("Zip Code" = zip,
            Employment = count,
            Share = share)%>%
    arrange(desc(Employment)) %>%
  kable(title = "Top 10 Zip Codes for Manufacturing", caption = "Top 10 Zip Codes for Manufacturing \n(Source: U.S. Census Bureau OnTheMap 2019)") %>%
  kable_styling("striped",full_width = F) %>%
  row_spec(1, background = '#95b8d1') %>%
  row_spec(2, background = '#b8e0d2') %>%
  row_spec(0, bold=TRUE) %>%
  column_spec(2, bold=TRUE)

health  %>% 
  summarize("Zip Code" = zip,
            Employment = count,
            Share = share)%>%
    arrange(desc(Employment)) %>%
  kable(title = "Top 10 Zip Codes for Health", caption = "Top 10 Zip Codes for Health \n(Source: U.S. Census Bureau OnTheMap 2019)") %>%
  kable_styling("striped",full_width = F) %>%
  row_spec(1, background = '#95b8d1') %>%
  row_spec(2, background = '#b8e0d2') %>%
  row_spec(0, bold=TRUE) %>%
  column_spec(2, bold=TRUE)

```

```{r Distance Direction, eval=TRUE, echo=TRUE, warning=FALSE, message=FALSE}
manufacturing_distance <- read_csv("manufacturing_distance.csv") 
manufacturing_home <- read_csv("manufacturing_home.csv") 

health_distance <- read_csv("health_distance.csv") 
health_distance <- health_distance %>%
  dplyr::select(Distance, Count, Share)
health_home <- read_csv("health_home.csv") 
health_home <- health_home %>%
  dplyr::select(city, count, share)

ggplot(manufacturing_distance, aes(x=reorder(Distance,Count), y=Count, fill = "#95b8d1" )) + 
  geom_bar(position="dodge", stat = "identity") +
  scale_fill_manual(name = "Count", values = palette) +
    scale_y_continuous(label=comma) +
  labs(x = "Distance",
         y = "Count",
         title = "Distance Traveled for Manufacturing Jobs in 90245",
       subtitle = "(Source: U.S. Census Bureau 2019)")

ggplot(manufacturing_home, aes(x=reorder(city,count), y=count, fill = "#95b8d1")) + 
  geom_bar(stat = "identity") +
    scale_fill_manual(name = "Count", values = palette) +
    scale_y_continuous(label=comma) +
  labs(x = "City",
         y = "Count",
         title = "Home City of People Travelling to 90245 for Manufacturing Jobs",
       subtitle = "(Source: U.S. Census Bureau OnTheMap 2019)") +
  coord_flip()

ggplot(health_distance, aes(x=reorder(Distance,Count), y=Count, fill = "#95b8d1", )) + 
  geom_bar(position="dodge", stat = "identity") +
  scale_fill_manual(name = "Count" , values = palette) +
    scale_y_continuous(label=comma) +
  labs(x = "Distance",
         y = "Count",
         title = "Distance Traveled for Health Jobs in 90024",
       subtitle = "(Source: U.S. Census Bureau OnTheMap 2019)")

ggplot(health_home, aes(x=reorder(city,count), y=count, fill = "#95b8d1")) + 
  geom_bar(stat = "identity") +
    scale_fill_manual(name = "Count", values = palette) +
  scale_y_continuous(label=comma) +
  labs(x = "City",
         y = "Count",
         title = "Home City of People Travelling to 90024 for Health Jobs",
       subtitle = "(Source: U.S. Census Bureau OnTheMap 2019)") +
  coord_flip()
```


